CREATE TABLE IF NOT EXISTS cf_local_message (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    topic VARCHAR(128) NOT NULL,
    tag VARCHAR(128),
    payload TEXT NOT NULL,
    status VARCHAR(32) NOT NULL DEFAULT 'NEW' COMMENT 'NEW, PUBLISHED, FAILED',
    retry_count INT DEFAULT 0,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    INDEX idx_status (status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='本地消息表';
