server:
  port: 8086
spring:
  application:
    name: post-loan-service

  data:
    redis:
      host: ${REDIS_HOST:redis}
      port: ${REDIS_PORT:6379}
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:mysql}:${MYSQL_PORT:3306}/${MYSQL_DATABASE:crediflow}?useSSL=false&characterEncoding=utf8&serverTimezone=UTC
    username: ${MYSQL_USER:crediflow}
    password: ${MYSQL_PASSWORD:crediflow}
  cloud:
    nacos:
      discovery:
        server-addr: ${NACOS_SERVER:nacos:8848}
        namespace: ${NACOS_NAMESPACE:}
        group: ${NACOS_GROUP:DEFAULT_GROUP}

crediflow:
  post-loan:
    penalty-rate: ${PENALTY_RATE:0.0005}


