CREATE TABLE IF NOT EXISTS cf_fund_flow (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    flow_no VARCHAR(64) NOT NULL UNIQUE,
    application_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    amount DECIMAL(18,4) NOT NULL,
    type VARCHAR(32) NOT NULL COMMENT 'DISBURSE, REPAY',
    status VARCHAR(32) NOT NULL DEFAULT 'PENDING' COMMENT 'PENDING, SUCCESS, FAILED',
    third_party_trade_no VARCHAR(128),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    INDEX idx_user_id (user_id),
    INDEX idx_application_id (application_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='资金流水表';

CREATE TABLE IF NOT EXISTS cf_mq_idempotent_log (
    message_id VARCHAR(128) PRIMARY KEY COMMENT 'MQ Message ID',
    topic VARCHAR(128) NOT NULL,
    tag VARCHAR(128),
    consumer_group VARCHAR(128) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='MQ防重日志表';
