server:
  port: 8081
spring:
  application:
    name: user-service
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:mysql}:${MYSQL_PORT:3306}/${MYSQL_DATABASE:crediflow}?useSSL=false&characterEncoding=utf8&serverTimezone=UTC
    username: ${MYSQL_USER:crediflow}
    password: ${MYSQL_PASSWORD:crediflow}
  flyway:
    enabled: true
    locations: classpath*:db/migration
crediflow:
  demo-mq-consumer: ${CREDIFLOW_DEMO_MQ_CONSUMER:false}
  cloud:
    nacos:
      discovery:
        server-addr: ${NACOS_SERVER:nacos:8848}
        namespace: ${NACOS_NAMESPACE:}
        group: ${NACOS_GROUP:DEFAULT_GROUP}
rocketmq:
  name-server: ${ROCKETMQ_NAMESRV:rmqnamesrv:9876}
  producer:
    group: user-service-producer
